version: '3.8'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'  # Монтируем текущую директорию
    # Убираем volume для node_modules
    command: npm run dev